export const GET_OWN_PLACES = "GET_OWN_PLACES";
export const GET_PLACES = "GET_PLACES";
export const EDIT_PLACE_SUCCESS = "EDIT_PLACE_SUCCESS";
export const EDIT_PLACE_ERROR = "EDIT_PLACE_ERROR";
export const CREATE_PLACE_SUCCESS = "CREATE_PLACE_SUCCESS";
export const CREATE_PLACE_ERROR = "CREATE_PLACE_ERROR";
export const DELETE_PLACE_SUCCESS = "DELETE_PLACE_SUCCESS";
export const DELETE_PLACE_ERROR = "DELETE_PLACE_ERROR";