export const GET_QUEUE_PEOPLE = "GET_QUEUE_PEOPLE";
export const GET_STATUSES = "GET_STATUSES";
export const EDIT_QUEUE_PERSON_SUCCESS = "CREATE_SET_NEXT_SUCCESS";
export const EDIT_QUEUE_PERSON_ERROR = "CREATE_SET_NEXT_ERROR";
export const DELETE_QUEUE_PERSON_SUCCESS = "DELETE_QUEUE_PERSON_SUCCESS";
export const DELETE_QUEUE_PERSON_ERROR = "DELETE_QUEUE_PERSON_ERROR";